apiVersion: v2
name: jenkins
home: https://jenkins.io/
version: 4.12.0
appVersion: 2.426.2
description: Jenkins

dependencies:
- name: jenkins
  version: 4.12.0
  repository: https://charts.jenkins.io
