apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testsoftware
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/urmas-villem/ClusterEyeGo.git
    targetRevision: HEAD
    path: kubernetes/Testsoftware/deployments
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
