kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clustereye
subjects:
  - kind: ServiceAccount
    name: clustereye
    namespace: default
roleRef:
  kind: ClusterRole
  name: clustereye
  apiGroup: rbac.authorization.k8s.io